function CreateSoundForGame takes nothing returns nothing
    set kD = CreateSound("war3mapImported\\BUTCHER.mp3", false, false, false, 10, 10, "")
    call SetSoundDuration(kD, 2268)
    call SetSoundChannel(kD, 0)
    call SetSoundVolume(kD, 127)
    call SetSoundPitch(kD, 1.0)
    set KD = CreateSound("war3mapImported\\Combowhore.mp3", false, false, false, 10, 10, "")
    call SetSoundDuration(KD, 2016)
    call SetSoundChannel(KD, 0)
    call SetSoundVolume(KD, 127)
    call SetSoundPitch(KD, 1.0)
    set lD = CreateSound("war3mapImported\\Dominating.mp3", false, false, false, 10, 10, "")
    call SetSoundDuration(lD, 1802)
    call SetSoundChannel(lD, 0)
    call SetSoundVolume(lD, 127)
    call SetSoundPitch(lD, 1.0)
    set LD = CreateSound("war3mapImported\\Double_Kill.mp3", false, false, false, 10, 10, "")
    call SetSoundDuration(LD, 2012)
    call SetSoundChannel(LD, 0)
    call SetSoundVolume(LD, 127)
    call SetSoundPitch(LD, 1.0)
    set mD = CreateSound("war3mapImported\\GodLike.mp3", false, false, false, 10, 10, "")
    call SetSoundDuration(mD, 1828)
    call SetSoundChannel(mD, 0)
    call SetSoundVolume(mD, 127)
    call SetSoundPitch(mD, 1.0)
    set MD = CreateSound("war3mapImported\\HolyShit.mp3", false, false, false, 10, 10, "")
    call SetSoundDuration(MD, 2325)
    call SetSoundChannel(MD, 0)
    call SetSoundVolume(MD, 127)
    call SetSoundPitch(MD, 1.0)
    set pD = CreateSound("war3mapImported\\Killing_Spree.mp3", false, false, false, 10, 10, "")
    call SetSoundDuration(pD, 2377)
    call SetSoundChannel(pD, 0)
    call SetSoundVolume(pD, 127)
    call SetSoundPitch(pD, 1.0)
    set PD = CreateSound("war3mapImported\\MegaKill.mp3", false, false, false, 10, 10, "")
    call SetSoundDuration(PD, 2612)
    call SetSoundChannel(PD, 0)
    call SetSoundVolume(PD, 127)
    call SetSoundPitch(PD, 1.0)
    set qD = CreateSound("war3mapImported\\MonsterKill.mp3", false, false, false, 10, 10, "")
    call SetSoundDuration(qD, 3344)
    call SetSoundChannel(qD, 0)
    call SetSoundVolume(qD, 127)
    call SetSoundPitch(qD, 1.0)
    set QD = CreateSound("war3mapImported\\Ownage.mp3", false, false, false, 10, 10, "")
    call SetSoundDuration(QD, 2586)
    call SetSoundChannel(QD, 0)
    call SetSoundVolume(QD, 127)
    call SetSoundPitch(QD, 1.0)
    set sD = CreateSound("war3mapImported\\Rampage.mp3", false, false, false, 10, 10, "")
    call SetSoundDuration(sD, 1728)
    call SetSoundChannel(sD, 0)
    call SetSoundVolume(sD, 127)
    call SetSoundPitch(sD, 1.0)
    set SD = CreateSound("war3mapImported\\triple_kill.mp3", false, false, false, 10, 10, "")
    call SetSoundDuration(SD, 1971)
    call SetSoundChannel(SD, 0)
    call SetSoundVolume(SD, 127)
    call SetSoundPitch(SD, 1.0)
    set tD = CreateSound("war3mapImported\\UltraKill.mp3", false, false, false, 10, 10, "")
    call SetSoundDuration(tD, 2556)
    call SetSoundChannel(tD, 0)
    call SetSoundVolume(tD, 127)
    call SetSoundPitch(tD, 1.0)
    set TD = CreateSound("war3mapImported\\Unstoppable.mp3", false, false, false, 10, 10, "")
    call SetSoundDuration(TD, 2038)
    call SetSoundChannel(TD, 0)
    call SetSoundVolume(TD, 127)
    call SetSoundPitch(TD, 1.0)
    set uD = CreateSound("war3mapImported\\WhickedSick.mp3", false, false, false, 10, 10, "")
    call SetSoundDuration(uD, 2612)
    call SetSoundChannel(uD, 0)
    call SetSoundVolume(uD, 127)
    call SetSoundPitch(uD, 1.0)
    set UD = CreateSound("war3mapImported\\firstblood.mp3", false, false, false, 10, 10, "")
    call SetSoundDuration(UD, 1541)
    call SetSoundChannel(UD, 0)
    call SetSoundVolume(UD, 127)
    call SetSoundPitch(UD, 1.0)
    set wD = CreateSound("Abilities\\Weapons\\AvengerMissile\\DestroyerMissile.wav", false, true, true, 10, 10, "MissilesEAX")
    call SetSoundParamsFromLabel(wD, "DestroyerMissileLaunch")
    call SetSoundDuration(wD, 817)
endfunction